sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm install -g npm-install-peers
install:
  - npm-install-peers
  - npm install
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test:coverage-travis
  - make dist
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
